# Generated by Django 3.2.7 on 2021-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelroom',
            options={},
        ),
    ]
